name: deploy project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dep
        run: npm i

      - name: publish
        run: vsce publish -p $DEPLOY_KEY -y